# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  modulesPath,
  ...
}: let
  commonUtils = import ../../utils/common.nix {inherit pkgs;};
in {
  imports = [
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  config = lib.mkMerge [
    (commonUtils.mkLxcConfig {
      hostname = "hl-lxc-homebridge";
      ipAddress = "192.168.1.10";
    })

    {
      # Runtime
      virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
      };

      myFolders = {
        homebridge = {
          path = "/var/lib/homebridge";
          owner = "root";
          group = "root";
          mode = "0755";
        };
      };

      # Enable container name DNS for all Podman networks.
      networking.firewall.interfaces = let
        matchAll =
          if !config.networking.nftables.enable
          then "podman+"
          else "podman*";
      in {
        "${matchAll}".allowedUDPPorts = [53];
      };

      virtualisation.oci-containers.backend = "podman";

      # Containers
      virtualisation.oci-containers.containers."homebridge-homebridge" = {
        image = "homebridge/homebridge:latest";
        volumes = [
          "/var/lib/homebridge:/homebridge:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network=host"
        ];
      };
      systemd.services."podman-homebridge-homebridge" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        partOf = [
          "podman-compose-homebridge-root.target"
        ];
        wantedBy = [
          "podman-compose-homebridge-root.target"
        ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-homebridge-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = ["multi-user.target"];
      };
    }
  ];
}
