name: Validate and Tag NixOS Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'hosts/**'
      - 'utils/**'
      - '.github/workflows/deploy.yml'

jobs:
  validate-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Validate NixOS configurations
        run: |
          # Check if configurations build
          for host in haproxy technitium; do
            echo "Validating configuration for $host..."
            nix flake check .#nixosConfigurations.$host
          done

      - name: Create deployment tag
        id: tag
        run: |
          # Create a tag with timestamp to mark a validated deployment
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TAG="deploy-${TIMESTAMP}"
          git tag $TAG
          git push origin $TAG
          echo "Created deployment tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Deployment ${{ steps.tag.outputs.tag }}
          body: |
            Validated NixOS configuration deployment.
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
